import { marked } from 'marked';
import type { ArticleRepository } from '../../domain/repositories/article-repository.ts';
import type { Article } from '../../domain/entities/article.ts';
import type { Result } from '../../domain/entities/result.ts';

export type ExportFormat = 'md' | 'html' | 'txt';

const HTML_TEMPLATE = ({
  title,
  body,
  createdAt,
  wordCount,
}: {
  title: string;
  body: string;
  createdAt: string;
  wordCount: number;
}) =>
  `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 18px; line-height: 1.8; color: #1d1d1f; max-width: 720px; margin: 0 auto; padding: 2rem 1.5rem; }
  header { margin-bottom: 2.5rem; }
  h1 { font-size: 2rem; line-height: 1.3; margin-bottom: .5rem; }
  .meta { color: #6e6e73; font-size: .875rem; }
  h2 { font-size: 1.5rem; margin-top: 2rem; margin-bottom: .75rem; }
  h3 { font-size: 1.25rem; margin-top: 1.5rem; margin-bottom: .5rem; }
  p { margin-bottom: 1.25rem; }
  a { color: #0066cc; }
  code { background: #f5f5f7; padding: .15em .4em; border-radius: 3px; font-size: .9em; }
  pre { background: #f5f5f7; padding: 1rem; border-radius: 8px; overflow-x: auto; margin-bottom: 1.25rem; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 3px solid #d2d2d7; padding-left: 1rem; color: #6e6e73; margin-bottom: 1.25rem; }
  ul, ol { margin-bottom: 1.25rem; padding-left: 1.5rem; }
  img { max-width: 100%; height: auto; border-radius: 8px; }
  hr { border: none; border-top: 1px solid #d2d2d7; margin: 2rem 0; }
  footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #d2d2d7; font-size: .8125rem; color: #6e6e73; }
</style>
</head>
<body>
<header>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">${createdAt} &middot; ${wordCount} words</p>
</header>
<main>${body}</main>
<footer>Generated by Thoth</footer>
</body>
</html>`;

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function stripMarkdown(md: string): string {
  return md
    .replace(/#{1,6}\s+/g, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/\[(.+?)\]\(.+?\)/g, '$1')
    .replace(/!\[.*?\]\(.+?\)/g, '')
    .replace(/>\s+/g, '')
    .replace(/[-*+]\s+/g, '')
    .replace(/\d+\.\s+/g, '')
    .replace(/---/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function formatArticleAsMarkdown(article: Article): string {
  const date = article.createdAt.toISOString().split('T')[0];
  return [
    '---',
    `title: "${article.title}"`,
    `date: ${date}`,
    `word_count: ${article.wordCount}`,
    `status: ${article.status}`,
    `id: ${article.id}`,
    '---',
    '',
    article.content,
  ].join('\n');
}

export function formatArticleAsHtml(article: Article): string {
  const date = article.createdAt.toISOString().split('T')[0];
  const body = marked.parse(article.content) as string;
  return HTML_TEMPLATE({ title: article.title, body, createdAt: date, wordCount: article.wordCount });
}

export function formatArticleAsTxt(article: Article): string {
  const date = article.createdAt.toISOString().split('T')[0];
  const plain = stripMarkdown(article.content);
  return [
    `Title: ${article.title}`,
    `Date: ${date}`,
    `Words: ${article.wordCount}`,
    `Status: ${article.status}`,
    '',
    plain,
  ].join('\n');
}

export interface ExportArticleInput {
  readonly articleId: string;
  readonly format: ExportFormat;
}

export interface ExportArticleOutput {
  readonly content: string;
  readonly filename: string;
}

export class ExportArticleUseCase {
  constructor(private readonly articleRepo: ArticleRepository) {}

  async execute(input: ExportArticleInput): Promise<Result<ExportArticleOutput>> {
    const articleResult = await this.articleRepo.get(input.articleId);
    if (!articleResult.ok) return articleResult;
    if (!articleResult.value) return { ok: false, error: `Article not found: ${input.articleId}` };

    const article = articleResult.value;
    const slug = article.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'article';
    let content: string;
    let ext: string;

    switch (input.format) {
      case 'md':
        content = formatArticleAsMarkdown(article);
        ext = 'md';
        break;
      case 'html':
        content = formatArticleAsHtml(article);
        ext = 'html';
        break;
      case 'txt':
        content = formatArticleAsTxt(article);
        ext = 'txt';
        break;
    }

    return {
      ok: true,
      value: { content, filename: `${slug}.${ext}` },
    };
  }
}
